### ISSUE TITLE
algorithm doesn't work with a high angular resolution of scans

### ISSUE THREAD

**Issue by vtretyakov** [kam3k/laser_line_extraction#14]
Hi, when I have an angular increment higher than 0.01 rad, the algorithm publishes the line markers in a circle at the max range of the scan message (I have a resolution of 0.0022 rad from my scanner, with a 270 degrees field of view). This problem can be easily reproduced both in simulation and on actual laser data. I tried all parameters, but apart from getting one small segment converging into line, nothing works. Any idea what I can try?

**Comment by kam3k** [comment]
Do you have a small bag file containing LaserScan data from that scanner to help figure this out?

**Comment by vtretyakov** [comment]
I've created one (attached as zip archive). The scan topic is _scan_merged_ on _base_link_. In the image you see my results. If I reduce the angular resolution, then the line extraction works.
![line_extraction_issue](https://user-images.githubusercontent.com/6347921/94243728-18e23f80-ff18-11ea-9af5-c7afc911d0c8.png)

[2020-09-25-10-09-18.zip](https://github.com/kam3k/laser_line_extraction/files/5281434/2020-09-25-10-09-18.zip)

**Comment by kam3k** [comment]
Thanks for the data. The issue was your data has a ton of points beyond the `range_max` and the algorithm was not properly ignoring data beyond `range_max`. I just pushed changes that added a `max_range` param. So in your launch file, add a `max_range` param and set it appropriately (50.0 for the data you provided). See `example.launch` for an example. A to-do here would be to set `max_range` automatically to be the `range_max` in the LaserScan message. I'll make an issue for this.

Anyway, here is a screenshot of your data with these changes, using the default settings except for a `max_range` of 50.0.
![line_extraction](https://user-images.githubusercontent.com/3095096/94272269-d9fcbb80-ff10-11ea-9650-473315b78944.png)

**Comment by vtretyakov** [comment]
The problem was not connected with the angular resolution at the end, very interesting. Thanks Marc @kam3k a lot for solving it! I pulled your changes a6f0d0bb4688743ea1f1ed6aef00701ddbc83019 and set the _max_range_ to 50m. It works perfectly! I'l close the issue.
